#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Setup instructions.

See: https://packaging.python.org/en/latest/distributing.html
"""

# ======================================================================
# :: Future Imports (for Python 2)
from __future__ import (
    division, absolute_import, print_function, unicode_literals)

# ======================================================================
# :: Python Standard Library Imports
import os  # Miscellaneous operating system interfaces
import re  # Regular expression operations
from codecs import open  # use a consistent encoding (in Python 2)

# ======================================================================
# :: Choice of the setup tools
from setuptools import setup
from setuptools import find_packages

# ======================================================================
# project specific variables
NAME = 'numeral'
VERSION_FILEPATH = os.path.join(NAME.lower(), '_version.py')
README_FILEPATH = 'README.rst'

# get the working directory for the setup script
CWD = os.path.realpath(os.path.dirname(__file__))

# get the long description from the README file
with open(os.path.join(CWD, README_FILEPATH), encoding='utf-8') as readme_file:
    LONG_DESCRIPTION_TEXT = readme_file.read()

VERSION_FILE_TEMPLATE = '''#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Package version file."""
# This file is automatically generated by `setuptools_scm` during setup.
__version__ = '{version}'
'''


# ======================================================================
# :: call the setup tool
setup(
    name=NAME.lower(),

    description='Support for various integer-to-numeral conversion.',
    long_description=LONG_DESCRIPTION_TEXT,

    # use_scm_version=True,
    # version=fix_version(),
    use_scm_version={
        'write_to': os.path.join(NAME.lower(), '_version.py'),
        'write_to_template': VERSION_FILE_TEMPLATE,
    },

    url='https://github.com/norok2/' + NAME.lower(),

    author='Riccardo Metere',
    author_email='rick@metere.it',

    license='GPLv3+',

    # See https://pypi.python.org/pypi?%3Aaction=list_classifiers
    classifiers=[
        'Development Status :: 4 - Beta',

        'Intended Audience :: Developers',
        'Intended Audience :: Science/Research',
        'Intended Audience :: Education',

        'Natural Language :: English',
        'Natural Language :: Latin',

        'Topic :: Software Development',
        'Topic :: Software Development :: Libraries',
        'Topic :: Software Development :: Localization',
        'Topic :: Text Processing',
        'Topic :: Text Processing :: Linguistic',
        'Topic :: Scientific/Engineering',
        'Topic :: Sociology :: History',
        'Topic :: Education',
        'Topic :: Utilities',

        'Operating System :: POSIX',

        'License :: OSI Approved :: GNU General Public License v3 or later'
        ' (GPLv3+)',

        'Programming Language :: Python',
        'Programming Language :: Python :: 2',
        'Programming Language :: Python :: 3',
    ],

    keywords=['numeral', 'letter', 'alphabet', 'numeric', 'arabic', 'roman'],

    packages=find_packages(exclude=['contrib', 'docs', 'tests']),

    setup_requires=[
        'setuptools',
        'setuptools_scm'
    ],
)
